export const CoursesData = [
  {
    id: 1,
    img: "https://images.pexels.com/photos/11035371/pexels-photo-11035371.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1 1x, https://images.pexels.com/photos/11035371/pexels-photo-11035371.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2 2x",
    name: "HTML",
    tags: "HTML",
    modules: 3,
    hours: 9,
    area: "Front",
    dificulty: "BASIC",
  },
  {
    id: 2,
    img: "https://colorlib.com/wp/wp-content/uploads/sites/2/creative-css3-tutorials.jpg",
    name: "CSS",
    tags: "CSS",
    modules: 3,
    hours: 9,
    area: "Front",
    dificulty: "ADVANCED",
  },
  {
    id: 3,
    img: "https://images.ctfassets.net/23aumh6u8s0i/2QjNmyDo6LfK4HC8F1q4qw/b8baddde46d79ec9432a15f14b4a41a2/javascript",
    name: "JavaScript",
    tags: "JavaScript",
    modules: 3,
    hours: 9,
    area: "Front",
    dificulty: "INTERMEDIATE",
  },
  {
    id: 4,
    img: "https://images.ctfassets.net/23aumh6u8s0i/3auCWvEHRgMULidrkY6oQx/44b6f250f482dc75323130492e322746/TS.png",
    name: "TypeScript",
    tags: "TypeScript",
    modules: 3,
    hours: 9,
    area: "Front",
    dificulty: "BASIC",
  },
  {
    id: 5,
    img: "https://images.unsplash.com/photo-1633356122102-3fe601e05bd2?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    name: "React",
    tags: "React",
    modules: 15,
    hours: 19,
    area: "Front",
    dificulty: "INTERMEDIATE",
  },
  {
    id: 6,
    img: "https://cdn.windowsreport.com/wp-content/uploads/2020/06/angular-logo-2.png",
    name: "Angular",
    tags: "Angular",
    modules: 15,
    hours: 35,
    area: "Front",
    dificulty: "ADVANCED",
  },
  {
    id: 7,
    img: "https://th.bing.com/th/id/R.df4c2f21e428850a4ee001c4e283a784?rik=M%2fDYAUEAYDdNIQ&pid=ImgRaw&r=0",
    name: "Vue js",
    tags: "Vue", 
    modules: 25,
    hours: 35,
    area: "Front",  
    dificulty: "ADVANCED",
},
  {
    id: 8,
    img: "https://th.bing.com/th/id/OIP.s5j5kFK-urpNTrVLlv9-ogHaEK?pid=ImgDet&rs=1",
    name: "Node js",
    tags: "Node",
    modules: 22,
    hours: 21,
    area: "Back",
    dificulty: "INTERMEDIATE",
  },
];

export const languages = [
  "PHP",
  "Perl",
  "Java",
  "C++",
  "Python",
  "JavaScript",
  "Swift",
  "R",
  "Rust",
];
